const NOTIFICATION_TYPE = {
    MIRRORED: "MIRRORED",
    QUOTED: "QUOTED",
    COMMENTED: "COMMENTED",
    FOLLOWED: "FOLLOWED",
    MENTIONED: "MENTIONED",
    REACTED: "REACTED",
    ACTED: "ACTED"
};

return {
    NOTIFICATION_TYPE
};